Do not build Catch2 tests
[why]
When building Catch2 as a subproject, its tests were automatically built
as well. This is not only time-consuming and unnecessary, but also
started to fail with the latest update of Apple clang:

../subprojects/Catch2-3.8.1/tests/SelfTest/UsageTests/Misc.tests.cpp:387:1:
error: no matching function for call to 'get_wrapper'

... because of an ambiguity related to std::tuple.

[how]
Simply disable building the Catch2 tests.