SmallVector: Add missing include and std prefix
[Why]
The compilation fails with:
> In file included from doocs-clientlib/src/EqAdr.cc:29:
> subprojects/gul17/include/gul17/SmallVector.h:277:22: error: 'uint32_t' does not name a type [-Wtemplate-body]
>   277 |     using SizeType = uint32_t;
>       |                      ^~~~~~~~
> subprojects/gul17/include/gul17/SmallVector.h:32:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
> ---8<---

Signed-off-by: Soeren Grunewald <soeren.grunewald@desy.de>